<?php

namespace App\Filament\Resources\Products\MasterProductResource\Pages;

use App\Filament\Resources\Products\MasterProductResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Str;

class CreateMasterProduct extends CreateRecord
{
    protected static string $resource = MasterProductResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['uuid'] = Str::uuid();
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

}
